table dim_date
	lineageTag: 87892108-2a30-45da-a076-3cec3293527e

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 92dfd82d-32a1-4e23-a941-d64a2aab7cde
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e45beb8-b9a9-47a3-9dc5-0223aa0ccea8
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: f03d9b2f-df69-41fc-baed-51fcabccf897
			defaultHierarchy: LocalDateTable_f0c84a88-6f8d-473c-af0a-bf14ae9e27ae.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: f6ebcc87-bca8-4fec-b1f3-ba7f3ef9df5f
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: abf9c65e-65f6-4954-a1ae-88042756e2c8
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: ad1a53fa-e931-40f1-b012-914df2aec33e
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 4ce9c77b-bb56-4818-a3f3-abf0bff68071
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		formatString: 0
		lineageTag: 5e99d65d-da54-4ba3-9af3-18d2e7e56e07
		summarizeBy: sum
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: int64
		formatString: 0
		lineageTag: fa24b6b2-0fc1-40de-a28e-6434d2088def
		summarizeBy: sum
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	column is_weekday
		dataType: int64
		formatString: 0
		lineageTag: 6fe1cb7a-61ac-4adf-9ef2-25e234f410d0
		summarizeBy: sum
		sourceColumn: is_weekday

		annotation SummarizationSetBy = Automatic

	column DateMonth = dim_date[year] * 100 + dim_date[month]
		dataType: int64
		formatString: 0
		lineageTag: 7985a053-743a-4025-9052-ef6697f5957c
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Mac\Home\Documents\AgencyPerformance\dim_date.csv"), [Delimiter = ",", Columns = 9, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"fiscal_year", Int64.Type}, {"fiscal_quarter", Int64.Type}, {"is_weekday", Int64.Type}})
				in
				  #"Changed column type"

